# Generated by Django 5.1 on 2024-08-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dados1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('dn', models.DateField()),
                ('endereço', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('curso', models.BooleanField(max_length=200)),
                ('img', models.ImageField(null=True, upload_to='./Imagens/')),
            ],
        ),
    ]
