# Generated by Django 5.1 on 2024-08-31 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_dados1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dados',
        ),
    ]
