# Generated by Django 5.1 on 2024-08-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_delete_dados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados1',
            name='dn',
        ),
        migrations.AlterField(
            model_name='dados1',
            name='curso',
            field=models.CharField(max_length=200),
        ),
    ]
