# Generated by Django 5.1 on 2024-08-31 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_remove_dados1_dn_alter_dados1_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados1',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='dados1',
            name='curso',
        ),
    ]
