# Generated by Django 5.1 on 2024-08-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_remove_dados1_cidade_remove_dados1_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='dados2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('endereço', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=300)),
                ('curso', models.CharField(max_length=300)),
                ('img', models.ImageField(null=True, upload_to='./Imagens/')),
            ],
        ),
        migrations.DeleteModel(
            name='dados1',
        ),
    ]
