# Generated by Django 5.1.2 on 2024-10-20 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_formservicos_servicos_delete_dados2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formservicos',
            old_name='mensagem',
            new_name='detalhes',
        ),
    ]
