# Generated by Django 5.1.1 on 2024-11-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0010_delete_solicitacao_formservicos_aceita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormServicos',
        ),
    ]
