# Generated by Django 5.1.1 on 2024-10-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sasa', '0008_rename_mensagem_formservicos_detalhes'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceita', models.BooleanField(default=None, null=True)),
            ],
        ),
    ]
